name: Check Clojure CA

on: [pull_request]

jobs:
  build:
    if: github.event.pusher.name != 'frenchy64'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('dev/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Check Clojure CA
        run: ./script/check-clojure-ca.sh ${{ github.event.pusher.name }}
