name: Check Clojure CA

on: [pull_request]

jobs:
  build:
    if: github.actor != 'frenchy64' && github.repository == 'typedclojure/typedclojure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-${{ hashFiles('dev/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 1.11
      - uses: DeLaGuardo/setup-clojure@38cb63c34a5d5d18e2b450cbb42432dbb1fb8612
        with:
          cli: 1.10.3.849
      - name: Check Clojure CA
        run: ./script/check-clojure-ca.sh ${{ github.actor }}
