name: Test and deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure: 
          - 1.10.1
          #- 1.11.0-master-SNAPSHOT
        jdk: 
          - 1.8
          #- 1.11
          - 1.13
        submodule:
          - typed/cljc.analyzer
          - typed/analyzer.js
          - typed/clj.analyzer
          #- typed/checker.js
          - typed/clj.checker
          - typed/clj.runtime
          - typed/annotator.jvm
          - typed/lang.jvm
          - typed/lib.clojure
          - typed/lib.core.async
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Run ${{ matrix.submodule }} tests
        run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version "${{ matrix.clojure }}"}}}'
        working-directory: ${{ matrix.submodule }}
  deploy:
    needs: test
    # this doesn't work
    #if: github.ref == 'master' && github.repository == 'typedclojure/typedclojure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest
      - name: Configure settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>clojars</id><username>typedclojure-clojars</username><password>${{ secrets.ClojarsPassword }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Deploy
        run: ./script/deploy-actions.sh
