name: Test and deploy

on: [push]

env:
  CLOJURE_CLI_VERSION: 1.10.1.727

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        clojure: 
          - 1.10.3
          #- 1.11.0-master-SNAPSHOT
        jdk: 
          - 1.8
          #- 1.11
          - 1.14
        submodule:
          - typed/cljc.analyzer
          - typed/cljs.analyzer
          - typed/clj.analyzer
          #- typed/cljs.checker
          - typed/clj.checker
          - typed/clj.reader
          - typed/clj.refactor
          - typed/clj.runtime
          - typed/clj.annotator
          - typed/clj.lang
          - typed/clj.spec
          - typed/lib.clojure
          - typed/lib.core.async
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-test-deps-${{ matrix.submodule }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }}-${{ env.CLOJURE_CLI_VERSION }} 
          restore-keys: |
            ${{ runner.os }}-test-deps-${{ matrix.submodule }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }}-
            ${{ runner.os }}-test-deps-${{ matrix.submodule }}-${{ hashFiles('**/pom.xml') }}-
            ${{ runner.os }}-test-deps-${{ matrix.submodule }}-
            ${{ runner.os }}-test-deps-
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
        with:
          cli: ${{ env.CLOJURE_CLI_VERSION }} 
      - name: Run ${{ matrix.submodule }} tests
        run: ./script/test -Sdeps '{:deps {org.clojure/clojure {:mvn/version "${{ matrix.clojure }}"}}}'
        working-directory: ${{ matrix.submodule }}
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.repository == 'typedclojure/typedclojure'
    runs-on: ubuntu-18.04
    env:
      DEPLOY_JDK: 11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-deploy-deps-${{ matrix.submodule }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }}-${{ env.CLOJURE_CLI_VERSION }} 
          restore-keys: |
            ${{ runner.os }}-deploy-deps-${{ matrix.submodule }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/deps.edn') }}-
            ${{ runner.os }}-deploy-deps-${{ matrix.submodule }}-${{ hashFiles('**/pom.xml') }}-
            ${{ runner.os }}-deploy-deps-${{ matrix.submodule }}-
            ${{ runner.os }}-deploy-deps-
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Set up JDK ${{ env.DEPLOY_JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.DEPLOY_JDK }}
      - uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
        with:
          cli: ${{ env.CLOJURE_CLI_VERSION }}
      - name: Configure settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>clojars</id><username>typedclojure-clojars</username><password>${{ secrets.ClojarsPassword }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Deploy
        run: ./script/deploy-actions.sh 
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
